### ISSUE TITLE
Certain Contact not loading

### ISSUE THREAD

**Issue by nate-moo** [iandwelker/smserver#48] opened 2020-10-27 19:43 UTC
I have a contact in my phone with prob around 600 numbers and that contact wont load in the web view but it is in my messages app. I can send screenshots if you would like. Additional information can also be provided if you need like logs etc.

**Comment by nate-moo** [comment] 2020-10-27 19:47
Device model - iPhone 8
Jailbreak (e.g. checkra1n, unc0ver, Chimera, etc) - Unc0ver
iOS Version - 13.5
How you installed the app - Zebra
A detailed description of what failed - Loading a specific contact
What version of SMServer & libsmserver you're running 0.5.1 & 0.4.0
And if the app crashed & you can get it, a crash log

**Comment by iandwelker** [comment] 2020-10-27 21:13
Just to clarify: When you say that it won't load, do you mean that it never appears on the list on the left side or that it does appear in the list but no texts load in when you click on it? Also, do any errors show in the browser's console when you run into this issue?

**Comment by nate-moo** [comment] 2020-10-28 00:27
![image](https://user-images.githubusercontent.com/40650681/97375988-97712a80-1892-11eb-8e4b-aa66f03e48e3.png)
All of the 410 numbers are supposed to be in one contact ^^
![image](https://user-images.githubusercontent.com/40650681/97376051-c4254200-1892-11eb-98ab-10cc8f04c6b1.png)
Here is the console ^^

**Comment by nate-moo** [comment] 2020-10-28 00:29
![image](https://user-images.githubusercontent.com/40650681/97376144-03ec2980-1893-11eb-965e-c66caf6ae723.jpeg)
The circled contact is what is supposed to show but instead I have all of those 410 numbers

**Comment by iandwelker** [comment] 2020-10-28 00:58
Yes, I'm following now &mdash; this is actually expected behavior. Each one of those numbers is stored as a separate conversation in the `sms.db` database on your phone (which SMServer communicates with), and SMServer doesn't list by contact, only by conversation. the iMessages app on your phone is smart and groups them all together based on contact, but SMServer is not that smart (yet). 

Resolving this will take some time, since I'll have to figure out exactly how these two databases relate and how to figure out what numbers/emails fall under the same contact (Ideally, all those numbers would be listed under the same contact in your contacts database, but since all of their 'names' in the web interface are different, I'd guess not).

If you know how to use sqlite (gui or terminal version), though, and are willing to help, there are some things that you could run to help me out with this issue. Just let me know.

**Comment by nate-moo** [comment] 2020-10-28 14:21
I could learn SQLite and help as much as I can, just tell me what I can do and I'll try to do it

**Comment by iandwelker** [comment] 2020-11-01 17:56
ok, so once you can run sqlite commands on your sms.db, run the following command and capture its output:
```sql
select c.c0First, c.c1Last, c.c2Middle, c.c3FirstPhonetic, c.c4MiddlePhonetic, c.c5LastPhonetic, c.c12Nickname, c.c15DisplayName, c.c16Phone, m.* from ABPersonFullTextSearch_content  c inner join ABMultiValue m on m.record_id = c.ROWID where c16Phone like "%1410100191%";
```
This command may output something that has some personal info, so if it does have some and you would rather not post it here, feel free to email it to me instead so that I can check it out.

**Comment by nate-moo** [comment] 2020-11-02 20:41
It cant find a table named ABPersonFullTextSerach_content
![image](https://user-images.githubusercontent.com/40650681/97917016-d5060580-1d21-11eb-9fa9-1a952fe4b872.png)

**Comment by nate-moo** [comment] 2020-11-02 20:41
here are the tables in sms.db
![image](https://user-images.githubusercontent.com/40650681/97917072-e9e29900-1d21-11eb-80ee-7e67c1fffb3b.png)

**Comment by iandwelker** [comment] 2020-11-02 20:42
so sorry, just realized I never specified that this needs to be run on your `AddressBook.sqlitedb` database (at `private/var/mobile/Library/AddressBook/AddressBook.sqlitedb` on your phone)

**Comment by nate-moo** [comment] 2020-11-02 20:49
ah its fine lemme do that real quick then

**Comment by nate-moo** [comment] 2020-11-02 20:52
![image](https://user-images.githubusercontent.com/40650681/97918020-66c24280-1d23-11eb-8952-6d62f6c8425d.png)
this doesn't seem right

**Comment by nate-moo** [comment] 2020-11-02 20:56
so looking through that table there aren't any phone numbers in any of the contacts so that should be correct then

**Comment by iandwelker** [comment] 2020-11-02 20:58
Hmm well if there was a contact in your phone with the number "1410100191", that should've grabbed all the relevant information about them. Some more questions, then: is "Iamresponding" listed as that contact's first name, last name, nickname or middle name? Also, just to clarify, `ABPersonFullTextSearch_content.c16Phone` never  contains a value? For any of your contacts? If that's the case, then you may just need to manually crawl through your `AddressBook.sqlitedb` to find where these phone numbers are stored, because `ABPersonFullTextSearch_content.c16Phone` and `ABMultiValue.value` are the only places that I see any phone numbers in my database.

**Comment by nate-moo** [comment] 2020-11-02 21:01
> Also, just to clarify, ABPersonFullTextSearch_content.c16Phone never contains a value?
yea nothing is there for any contact, it has all of the emails but no phone number

>  Some more questions, then: is "Iamresponding" listed as that contact's first name, last name, nickname or middle name?
it is the first name of the contact

**Comment by nate-moo** [comment] 2020-11-02 21:10
ok now there are phone numbers, that was weird

**Comment by iandwelker** [comment] 2020-11-02 21:14
Hmm well then could you run 
```sql
select c.c0First, c.c1Last, c.c2Middle, c.c3FirstPhonetic, c.c4MiddlePhonetic, c.c5LastPhonetic, c.c12Nickname, c.c15DisplayName, c.c16Phone, m.* from ABPersonFullTextSearch_content  c inner join ABMultiValue m on m.record_id = c.ROWID where c0First like "%Iamresponding%";
```
and paste the output?

Also, if you'd like a temporary solution, you can get the `id` values for all the conversations listed in the web interface and set a custom css file that sets all their `display` attributes to `none`, e.g.:
```css
#1410100191 {
    display: none
}
```

**Comment by nate-moo** [comment] 2020-11-02 21:18
so... it was too long for my terminal

**Comment by iandwelker** [comment] 2020-11-02 21:20
Would it be possible to output it to a file? e.g. run (from your shell):
```bash
sqlite3 ./AddressBook.sqlitedb 'select c.c0First, c.c1Last, c.c2Middle, c.c3FirstPhonetic, c.c4MiddlePhonetic, c.c5LastPhonetic, c.c12Nickname, c.c15DisplayName, c.c16Phone, m.* from ABPersonFullTextSearch_content c inner join ABMultiValue m on m.record_id = c.ROWID where c0First like "%Iamresponding%";' > output.txt
```

**Comment by nate-moo** [comment] 2020-11-02 21:21
yea I just did that as you said that

**Comment by nate-moo** [comment] 2020-11-02 21:23
it created a nice 45mb file

**Comment by iandwelker** [comment] 2020-11-02 21:26
That's significantly larger than I would've expected... is your AddressBook.sqlitedb file even 45mb itself? (mine is < 1mb) Also, is it all text or is there somehow like a hexdump in there somewhere? I doubt that whole file is relevant, so maybe you could poke through through it and try to see what's up?

**Comment by nate-moo** [comment] 2020-11-02 21:31
I mean, it seems normal besides the weird spacing of the numbers

**Comment by nate-moo** [comment] 2020-11-02 21:32
https://1drv.ms/t/s!Am_MW6x59iGrgbcR7NCM3Gxuw6feJQ?e=yDVkY3
here is a link to the file

**Comment by nate-moo** [comment] 2020-11-02 21:33
might just want to download it and view it locally because onedrive's viewer has a seizure trying to read it

**Comment by nate-moo** [comment] 2020-11-02 21:35
my address book is 1.8mb

**Comment by iandwelker** [comment] 2020-11-02 21:56
So it appears your phone contains ~1300 entries for this same contact, with thousands of phone numbers for each of them. The numbers are spaced out weird so that that field contains basically every possible substring of each of the contact's numbers, separated by spaces.
I can definitely look into solutions to fix this problem and condense all the numbers into one contact, but I don't know if I'll be able to get it pushed out any time soon, and I would expect it to cause a noticeable performance hit in loading the list of chats (since it has to cross-reference all the numbers with the contact database). However, I may be able to do it without noticeably impacting performance; I'll keep my progress updated in this task. If you come across any more information that you feel is relevant or could help, feel free to put it here.

**Comment by nate-moo** [comment] 2020-11-02 22:04
Jsyk the weird spacing was a fault of me as I just used a google sheet to add every number in for that contact instead of doing it manually. Other than that I dunno. There could be an option in the app which enables loading contacts with entries above a certain noticeable threshold. If it's unchecked it would do what it does now

**Comment by iandwelker** [comment] 2020-11-02 22:11
That's what I'm considering doing -- I doubt that most people are in a situation similar to yours, so I could add optional cross-checking with the Address book to concatenate contacts into a single conversation (for situations like yours), but leave it unchecked by default since most people don't need that increased level of accuracy and it would just hurt the app's speed for them.

**Comment by nate-moo** [comment] 2020-11-03 02:53
Thanks for doing this though, I appreciate it a lot.

**Comment by iandwelker** [comment] 2020-11-07 02:06
https://byu.box.com/s/95k04zzgi5jwzbfa4k8j666o0e2937zp -- This link contains a version that should hopefully implement this feature. Once you install it, you'll just have to enable the `Merge contact addresses (slower)` toggle in settings, load up the web interface, and hopefully all of those numbers will be shown as one entry on the list. Could you try it out and let me know if it worked? (I'm just sharing it here in cases it doesn't work at all with a contact book like yours; I'd like to verify at least base functionality for this feature before releasing it)

**Comment by nate-moo** [comment] 2020-11-07 22:06
It didn't work, I toggled the option but nothing changed on the web server

**Comment by iandwelker** [comment] 2020-11-24 02:48
How about [this version](https://byu.box.com/s/nqtc9bwugtyinpdmtttemgeojjugf9og)? Does it fix the issue at all once you've toggled the option on and reloaded the web interface?

**Comment by iandwelker** [comment] 2021-01-31 04:11
This issue was fixed in Version 0.6.0 and it's been stale for quite a while. Closing now.

**Closed by iandwelker** 2021-01-31 04:11 UTC

**Comment by nate-moo** [comment] 2021-01-31 04:12
I ended up switching to android. Thanks for all your help in the past though.

**Comment by iandwelker** [comment] 2021-01-31 04:13
Yeah, no problem. Thanks for supporting the project :)
