### ISSUE TITLE
Messages Not Loading

### ISSUE THREAD

**Issue by creditcreate** [iandwelker/smserver#8] opened 2020-08-13 06:34 UTC
Hello,

iPhone 11 - iOS 13.5 - unc0ver

- App works swimmingly fine
- Loading onto all browsers is fine (Chrome, Mozilla, Edge, Brave)
- I'm able to send messages using the ' new composition box' and typing the recipient's number manually
- **Previous chats and currently received messages aren't loading up**  

From our reddit conversation,

1. Are there any errors in your browser's console?  **There are no errors in either browser I have attempted to log onto**
2. Did the app crash or freeze when you tried to visit the website?  **The app nor the browser crashes or freezes**
3. If you visit the address that displays in the main section of the app, but append "/requests?chat=0" onto the end (so the address, altogether, will look something like "192.168.xx.xx:8741/requests?chat=0"), what shows up?  

```
{ "chats": [

]
}
```

**Comment by iandwelker** [comment] 2020-08-13 06:40
This seems like it could be a duplicate of #7. Could you check that out and let me know if it seems to describe your issue as well?

**Comment by creditcreate** [comment] 2020-08-13 13:04
My issue seems very similar to #7 and the only difference I really see is we have different phone models and I'm unsure if he can send messages using the 'new composition box'. If it's similar enough, then I will close this issue.

**Comment by nate-moo** [comment] 2020-08-13 13:55
I just tested it and yes, I am able to send messages through the new box

**Comment by iandwelker** [comment] 2020-08-13 14:11
Ok, so it looks like this is a duplicate. I'm going to close it; I'll close this one, and @creditcreate could you add your information about this to the other issue?

**Closed by iandwelker** 2020-08-13 14:11 UTC
