### ISSUE TITLE
Issue: Unable to load web panel

### ISSUE THREAD

**Issue by PhoenixAceVFX** [iandwelker/smserver#86] opened 2021-02-08 11:37 UTC
So I have gone through every issue thats on the github yet I cannot get the web panel to load despite everything I have tried. I have a IPhone 6s running iOS 13.5.1 jailbroken with Checkra1n
I'm not exactly sure what im even doing wrong at this point.

**Comment by PhoenixAceVFX** [comment] 2021-02-08 11:39
![image](https://user-images.githubusercontent.com/38572203/107214750-60093280-69d8-11eb-8fba-77a758ea6a55.png)
This is the issue im getting consistently

**Comment by PhoenixAceVFX** [comment] 2021-02-08 11:59
I installed it via sileo from the twickd repo and im on the latest smserver and libsmserver

**Comment by iandwelker** [comment] 2021-02-08 15:15
The [FAQ](https://github.com/iandwelker/smserver/blob/master/docs/FAQ.md) has some things you should consider when running into this issue. Could you look at the questions it lists and answer all of them in a comment here?

**Comment by PhoenixAceVFX** [comment] 2021-02-08 16:21
Have you made sure to install all of the dependencies (specifically libsmserver and libMRYIPC)? | Installed both of them and they're up to date
Did you start the server with the green button on the bottom left of the app? | Yes I did
Are you connecting to the right address with regard to using https:// vs http://? | Yes I am
Are your host and client devices on the same LAN/WLAN networks? | Yes they are
Did you verify that neither device's firewall is blocking the connection? | Yep, I personally allowed the connection

**Comment by CSab6482** [comment] 2021-02-08 19:27
> ![image](https://user-images.githubusercontent.com/38572203/107214750-60093280-69d8-11eb-8fba-77a758ea6a55.png)
> This is the issue im getting consistently

For me, https was finicky so I switched to http and everything worked fine

**Comment by PhoenixAceVFX** [comment] 2021-02-09 01:19
I tried switching to http, same result

**Comment by iandwelker** [comment] 2021-02-10 17:04
Have you tried any other browsers?

Also, would you be able to test out the [terminal client](https://github.com/iandwelker/smserver_receiver)? I understand you may not want to use it full-time, I just think testing it out would help us to determine what the root cause of this issue is.

**Comment by PhoenixAceVFX** [comment] 2021-02-11 02:21
i mean i cant test it now because my phone kinda bricked itself so now im on an unjailbroken iphone that decided to forcefully (i say that because it just decided to update on its own) to the latest ios so im shit out of luck currently until i can remember how to downgrade to 13.5.1 again

**Comment by PhoenixAceVFX** [comment] 2021-02-11 14:15
ok so i cant even use the terminal client it just crashes on load (probably cause i suck at python lol)
i downgraded my phone again so I went through a few of the suggestions.
I cant even get oslog due to an error of "unsupported"
so i cant even grab any data of whats going on sadly.
I'm not really sure whats causing it at this point but ive went through everything i could so I dont know where to go from here.

**Comment by PhoenixAceVFX** [comment] 2021-02-11 14:21
though from what it looks like (used netlimiter to get to this point) I believe my computer IS trying to connect but for some unknown reason the connection does not want to fully go through.
there IS communication but I cant seem to figure out why its refusing to load the page (this is happening both with and without SSL
https://phoenix.femboy.best/BHxcgRp6

**Comment by iandwelker** [comment] 2021-02-13 07:06
Have you tried another browser or device? And have you tried connecting to the server in the host device's own browser?

Also, is your device connected to your computer via usb? It *shouldn't* affect anything, but I've seen it occasionally cause issues with connecting in the past.

**Comment by PhoenixAceVFX** [comment] 2021-02-14 03:12
different devices and browsers yield the same result except on the host device
USB cable didn't make a difference connected or disconnected

**Comment by iandwelker** [comment] 2021-02-23 21:16
Sorry, I've been thinking about this and I don't know if there's anything else I can do &mdash; if you can connect to SMServer's web interface on the host device, then this sounds like a network problem, and not an SMServer problem (since the server is clearly running and accepting connections). If you have reason to believe there's something wrong with SMServer that would be causing this (as opposed to something else within your network), we can keep this issue open. However, I don't see how that could be the case.

**Comment by iandwelker** [comment] 2021-03-23 05:17
If there's more you think I can do, feel free to reopen this. However, it sounds like an issue out of the domain of SMServer, so I'm closing this issue.

**Closed by iandwelker** 2021-03-23 05:17 UTC
Labels: bug
