### ISSUE TITLE
Creating a group chat causes all numbers to concatenate together

### ISSUE THREAD

**Issue by Sergster1** [iandwelker/smserver#118] opened 2021-04-07 00:19 UTC
+1234567890, +0987654321 becomes 
+12345678900987654321

**Comment by iandwelker** [comment] 2021-04-10 17:29
Thanks for catching that! It was caused by a workaround from a bit ago; it should be fixed with the next update.

**Comment by iandwelker** [comment] 2021-05-03 03:40
This is fixed in version 0.8.0. Closing.

**Closed by iandwelker** 2021-05-03 03:40 UTC
Labels: bug, update pending
