### ISSUE TITLE
[Feature Request] Emoji Mart or something similar

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#115] opened 2021-03-27 00:41 UTC
Windows autocorrects some emojis to emoticons, so I was wondering if it would be possible to implement something like Emoji Mart for this
![Emoji Mart SMServer](https://user-images.githubusercontent.com/53708281/112705117-b42a8200-8e73-11eb-8420-6d20a16f3290.png)
![Emoji](https://user-images.githubusercontent.com/53708281/112705081-91986900-8e73-11eb-9a96-ad144186341e.jpg)

**Comment by iandwelker** [comment] 2021-03-27 08:10
I don't think I quite follow what you're requesting here. Apple emojis on Windows? An emoji picker built-in to the web interface?

**Comment by CSab6482** [comment] 2021-03-27 10:54
The second one. An emoji [picker](https://github.com/missive/emoji-mart)/[viewer](https://missive.github.io/emoji-mart/)

**Comment by iandwelker** [comment] 2021-03-27 18:20
This request was already brought up in issue #42, and I gave my thoughts on it there. As of right now, I intend to keep SMServer without an emoji picker, but if you feel there are points that we didn't consider in that last issue, feel free to bring them up and we can discuss them.

**Comment by CSab6482** [comment] 2021-03-27 21:24
I think your original thoughts are good, and I was wondering if SMServer still uses the internet to access Font Awesome. I feel like using a third party emoji picker would help in use cases like the one in this ticket where the emoji doesn't display properly with the native emoji set (Emoji Mart also has the option for using the native system emojis). However, if SMServer is independent of Font Awesome's internet dependency, then yes I think it would be best to leave the emoji situation alone, but if the app already requires the internet for some assets, then I think adding an emoji picker would be helpful (maybe even making it opt-in). But it's also a case of how difficult it would be to implement and if it would cause any slowdowns, as well as the fact that you would then have to depend on the third party to keep the emojis up to date (e.g. Unicode 13).

**Comment by CSab6482** [comment] 2021-03-27 21:30
Here's another small issue with emoji vs. emoticon on Windows
![Emoji SMServer](https://user-images.githubusercontent.com/53708281/112735407-1f329200-8f22-11eb-965f-0c1d125f8299.png)
![Emoji Picker](https://user-images.githubusercontent.com/53708281/112735409-1f329200-8f22-11eb-808e-4d4b086afe40.png)

**Comment by CSab6482** [comment] 2021-04-08 22:28
https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/193#issuecomment-816248349

**Comment by iandwelker** [comment] 2021-06-28 06:58
Super late response but here it goes:

> I was wondering if SMServer still uses the internet to access FontAwesome

It actually doesn't anymore. In version 0.6.3, I moved FontAwesome offline so that you once again don't have to connect to the internet at all to fully use the app as intended.

> I feel like using a third party emoji picker would help in use cases like the one in this ticket where the emoji doesn't display properly with the native emoji set

That would be kinda nice, I'll admit; apple emojis are very superior to windows/noto color emojis and I would like to be able to see them, but I don't think that's enough of a reason, personally.

I'm currently working on adding built-in support for out-of-network access, so the whole "*don't need internet to use the app*" may not be as important for the app in the future, but I don't plan on working with this specific issue anytime soon, so I'm going to close it for now and reopen if I ever decide this should be implemented in the app.

**Closed by iandwelker** 2021-06-28 06:58 UTC
Labels: enhancement
