### ISSUE TITLE
Springboard crash to safe mode on reacting to message

### ISSUE THREAD

**Issue by astra-io** [iandwelker/smserver#66] opened 2020-12-14 22:07 UTC
Will try and get logs later.
ipx 11 max pro 13.5
odyssey / libhooker

**Comment by iandwelker** [comment] 2020-12-14 22:55
Ah, yes &mdash; unfortunately, I have no way of testing message tapbacks on iOS 13-. The method that is used to send tapbacks on iOS 14+ is different from the method that is used on iOS 13-, and I only have a device on iOS 14+, so I can't test and figure out exactly what is needed to send tapbacks on iOS 13-. I included a method that I was fairly certain would work, but it appears, due to this report, that it doesn't work. However, crash logs could possibly point to why it doesn't work, so I would still appreciate it if you could get those.

**Comment by gnawh** [comment] 2020-12-24 00:42
in the interim, can we have an option to remove this feature? it's also impossible to copy and paste a message if once we click it, it'll give us that pop up (which still crashes).

**Comment by iandwelker** [comment] 2020-12-27 02:07
Yeah, I'll definitely add an option to not show the tapback dialog.

**Comment by iandwelker** [comment] 2021-01-10 04:56
A quick update on this issue &mdash; I was not able to implement something to disable sending tapbacks from the web interface for the latest version (0.7.0), but I may have fixed the SpringBoard crash. Could you try it out and let me know?

**Comment by gnawh** [comment] 2021-01-10 09:59
Failed to send tapback: Bad Request
400 Bad Request obviously on the GET request.
Glad that it doesn't crash though!

**Comment by iandwelker** [comment] 2021-01-10 17:09
Interesting, I'm not running into the same thing. Could you do the following:
1. Open the SMServer web interface and open the browser console (right click > inspect or inspect element > console)
2. Type in `debug = true` and hit enter
3. Try to send a tapback
4. You should see a message appear in the console along the lines of `getting text from url send?tapback=1&tap_guid=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX&tap_in_chat=+11231231234&remove_tap=false`. Could you copy that whole message and paste it here?

**Comment by CSab6482** [comment] 2021-01-11 01:13
![20210110_182226](https://user-images.githubusercontent.com/53708281/104138274-0aa61b00-5371-11eb-8988-ab9af8802677.jpg)
Last night I had this happen on just about every tapback I sent. Today that number went down to about 1 in 5, but as the title says, one failure was enough to send my phone into safe mode. Let me know what settings I can turn on/logs I can send for better debugging (I also did a full uninstall/reinstall of both SMServer and libsmserver)

**Comment by iandwelker** [comment] 2021-01-11 19:51
An update: I've realized that version 0.7.0 had some incorrect error checking that prevents you from sending the `heart` or `question mark` tapbacks. The others should work just fine, and I still have yet to figure out what's causing the crash. @gnawh , would you be able to try out one of the middle tapbacks (for example, the laughing or thumbs down) and let me know if they go through or if they continue to crash SpringBoard?

**Comment by iandwelker** [comment] 2021-02-10 17:12
I've got confirmation from some other users that tapbacks now work fine on all supported versions. Closing.

**Comment by CSab6482** [comment] 2021-02-11 04:14
![image](https://user-images.githubusercontent.com/53708281/107601818-b99a7880-6bf5-11eb-9762-0a9bc38976fd.png)
I just got this while trying to add a tapback to a link on version 0.7.2

**Comment by iandwelker** [comment] 2021-02-12 19:10
Huh. Well, I guess I don't have everything sorted out. 

Has this been a recurring issue? And which tapback were you trying to send? And could you remind me again, what jailbreak/iOS version are you running?

**Comment by CSab6482** [comment] 2021-02-12 19:12
That happened when I tried to add a heart to a message. I'm currently on iOS 14.4 on an iPhone 6S using odysseyn1x v2.9 (based on checkra1n 0.12.2)

**Comment by CSab6482** [comment] 2021-02-13 06:39
![Error](https://user-images.githubusercontent.com/53708281/107843785-eab4ad80-6d9b-11eb-9643-3ed72dac8b88.JPG)
I got this just now on attempting to add a heart to a message. After a respring, the message had an emphasis on it and I had no trouble switching that to a heart

**Comment by CSab6482** [comment] 2021-02-18 02:33
![Laugh](https://user-images.githubusercontent.com/53708281/108296471-9d538a00-7167-11eb-9f0c-b02dbf6401cd.JPG)
I got this while adding a laugh to a message, and while I did need to close SMServer from my app switcher and reopen it, I wasn't sent into safe mode.

![Heart (SM)](https://user-images.githubusercontent.com/53708281/108296508-ad6b6980-7167-11eb-98ac-ff76e65c1d5d.JPG)
This happened with a heart and I was sent into safe mode.

iPhone 6S, iOS 14.4, odysseyn1x 2.9 (based on checkra1n 0.12.2), SMServer 0.7.2

**Comment by iandwelker** [comment] 2021-02-18 04:03
Do you happen to have any SpringBoard crash logs from these instances that you could post here? It would help immensely if you could get any.

**Comment by CSab6482** [comment] 2021-02-18 04:37
I'd be happy to supply any logs and I'll remember it for the next time this happens. How do I retrieve those logs?

**Comment by iandwelker** [comment] 2021-02-18 17:30
You can get them through an app like cr4shed, or by going to Settings > Privacy > Analytics & Improvements > Analytics Data in the settings app of your phone.

**Comment by CSab6482** [comment] 2021-02-20 22:36
![Crash test](https://user-images.githubusercontent.com/53708281/108610228-1dfdca80-73a2-11eb-9ccf-340b6838e0ad.JPG)
I tested six different chats with a multitude of tapbacks, all with no errors. From a bug persepctive that's good since it is working as intended, but I'll look out for any crashes and send you the logs right away if it happens again

**Comment by iandwelker** [comment] 2021-02-20 23:44
Well that's good to hear; if you don't run into any more crashes due to this in let's say a week, I think we'll be good to close this issue. Of course, if you do run into one, I'll totally look over the crash logs and try to figure out the issue.

**Comment by CSab6482** [comment] 2021-02-20 23:45
> Well that's good to hear; if you don't run into any more crashes due to this in let's say a week, I think we'll be good to close this issue. Of course, if you do run into one, I'll totally look over the crash logs and try to figure out the issue.

Is there any way to install an old build for testing purposes just to be able to see what was causing it anyways?

**Comment by iandwelker** [comment] 2021-02-20 23:52
Yeah, if you download an old .deb package from under `Releases` in this repo, you can install that to your phone through filza or something similar. You'll just have to make sure that the version of libsmserver which you're using is compatible with it. SMServer 0.7.0 - 0.7.3 should be compatible with libsmserver 0.6.0 - 0.6.3, respectively (e.g. 0.7.0 with 0.6.0, 0.7.1 with 0.6.1, etc)

**Comment by CSab6482** [comment] 2021-02-21 00:20
Would I need to install an older bersion of libsmserver, or no? So, for example can I use SMServer 0.7.2 with libsmserver 0.6.3?

**Comment by CSab6482** [comment] 2021-02-21 00:54
[Tapback 0.7.2 Crash.txt](https://github.com/iandwelker/smserver/files/6016915/Tapback.0.7.2.Crash.txt)
[Tapback Springboard Crash.txt](https://github.com/iandwelker/smserver/files/6016916/Tapback.Springboard.Crash.txt)
I got it to crash on 0.7.2, here are my logs

**Comment by CSab6482** [comment] 2021-02-22 19:52
[Emphasis Crash 0.7.3.txt](https://github.com/iandwelker/smserver/files/6024787/Emphasis.Crash.0.7.3.txt)
This was my first time receiving the crash on version 0.7.3 while sending an emphasis from an iPhone 11

**Comment by iandwelker** [comment] 2021-03-23 05:19
@CSab6482 I redid this part of the backend in version 0.7.4 &mdash; could you try it out and update this issue if you run into the bug at all anymore (or close the issue if it stops appearing)?

**Comment by CSab6482** [comment] 2021-03-23 05:21
I had this happen once on version 0.7.3 and that was it. I don't have the ability to close this ticket, but if I could I would, and then I would just comment or reopen if I had it happen again

**Comment by iandwelker** [comment] 2021-03-23 05:27
Alright, well I'm always happy to close issues :)

**Closed by iandwelker** 2021-03-23 05:27 UTC
Labels: bug
