### ISSUE TITLE
messages from non-numeric SMS "numbers" don't get displayed

### ISSUE THREAD

**Issue by blanxd** [iandwelker/smserver#14] opened 2020-08-18 18:44 UTC
(public version 0.3.3)
If the SMS sender is using an `SMS Sender ID` string as the _From address_ instead of a regular phone number, clicking on that name in the web gui won't retrieve the corresponging messages.
Eg. `/requests?person=paypal&num=200` returns 
```
{ "texts": [

]
} 
```
I suppose it's the logic in ChatDelegate.swift L350-L354, where the `check_string` with such a request becomes `chat_identifier like "_" or chat_identifier is ""`, because it's neither a `chat...` or an email address, nor does it contain any numbers (it might contain all sorts of chars, including numbers and the space).

**Comment by iandwelker** [comment] 2020-08-18 19:10
Thanks for pointing this out, and that's definitely where the issue is -- I actually made that special logic for comparing phone numbers differently than group chats and emails as a workaround for another issue I was running into, but I fixed that other issue (specifically, the web framework I was using would remove special characters like plus signs when parsing url queries, but I rewrote the query parsing in the problematic areas so that plus signs don't get filtered out), so I don't need it anymore. I'll just replace all that special parsing with `chat_identifier is <num>`, and that should fix the issue.

**Comment by blanxd** [comment] 2020-08-19 01:42
cool. I was close to proposing something similar, but I thought there were some other edge cases for other types so didn't know what the exact thinking was behind all that, but this explains it :)

**Comment by iandwelker** [comment] 2020-08-19 15:07
v0.3.4 is out now, it should fix this. Could you try it and let me know?

**Comment by londondev77** [comment] 2020-08-19 15:20
Looking good now and the capitalisation of the sender is correct too!

**Comment by iandwelker** [comment] 2020-08-19 15:52
Glad to hear. I'll wait for @blanxd to confirm and close the issue if all looks good.

**Comment by blanxd** [comment] 2020-08-19 17:10
Yeap, I don't see any functional bugs any more.
This is indeed, one extremely useful tweak/system!

**Comment by iandwelker** [comment] 2020-08-19 17:19
Thanks, I appreciate it :) I'll close this issue, then.

**Closed by iandwelker** 2020-08-19 17:19 UTC
