### ISSUE TITLE
SMServer crashes when trying to send file or image

### ISSUE THREAD

**Issue by joshHuang02** [iandwelker/smserver#36] opened 2020-09-14 22:18 UTC
As described in title. This used to work in a previous version sometime ago but it doesn't work now. The SMServer iPhone app also exits when it crashes. 
SMServer 0.4.0
libsmserver 0.3.3

SMServer crashlog here: https://pastebin.com/Vzm0WgYx

MobileSMS crashlog here: https://pastebin.com/Hdgsja2V

*Side request: can you make it allow pasting image or files into the type box

**Comment by iandwelker** [comment] 2020-09-14 22:36
Thank you so much for posting an issue about this, and including the MobileSMS crash log. For some reason, I didn't even think to check that. I found the issue (if you're interested, it was that everything in `- (void)sendText:` in libsmserver has to be run on the main thread; I wasn't doing that). I've fixed that up, and I'll hopefully have a new update (with that fixed) shipped out by tonight or tomorrow.

With regards to pasting: I can probably implement that (I don't think I'll do so in this version, but later on), but I don't think it'll have the images visually appear in the textbox; that would be too much work for too little return. I can probably have the total number update in the attachment box in the side, though.

**Comment by joshHuang02** [comment] 2020-09-14 22:43
Thanks for the quick work! For pasting, I think no visual image is perfectly fine. Just having the functionality itself is a huge convenience when sending windows screenshots through iMessage.

**Comment by iandwelker** [comment] 2020-09-15 05:01
The new versions (of SMServer and libsmserver) have now been submitted to Twickd; try them out when they become available to you and let me know if they fix this issue for you as well. If the issue is fixed, we can change the name of this issue and keep it open until I add the pasting functionality.

**Comment by joshHuang02** [comment] 2020-09-15 05:52
The choosing file part is fixed but choosing image from phone crashes SMServer. Still didn't work after reinstall and rejailbreak. 

SMServer crashlog here: https://pastebin.com/pDFuqmzR

**Comment by iandwelker** [comment] 2020-09-16 05:03
Hmmm yeah that's really interesting. Are you certain that you've allowed SMServer access to your camera roll? 

If you have, I think I may have found the issue and I added some error checking that should fix the issue in the next version.

**Comment by joshHuang02** [comment] 2020-09-16 08:11
I don't remember allowing SMServer to access my camera roll recently. But based on the fact that selecting photos used to work for me, I think I allowed it the first time I used it.

**Comment by iandwelker** [comment] 2020-09-17 02:14
I just updated the app to 0.4.2 on Twickd; try it out when it becomes available to you and let me know if it fixes it

**Comment by londondev77** [comment] 2020-09-17 08:18
Mine no longer crashes when I bring up the camera roll however now the image thumbnails are all broken.  Looks like the URL to each thumbnail /data?photo=nil.

Debug log shows:
`Getting photo data from path nil`

I only have a few photos as I'm running SMServer on my iPad but let me know if I can help you debug

**Comment by joshHuang02** [comment] 2020-09-17 09:24
Not sure why twicked took forever to show the update but just tested and sending single/multiple images from camera roll and files work just fine. I had a similar thing with the loading images problem mentioned above (some photos are small no image icons). I use iCloud photos and most of my photos are stored in iCloud instead of on device. It seems that I can only see and select photos on my device. After downloading the original photos from iCloud and refreshing the webpage I can see and select them.

**Comment by joshHuang02** [comment] 2020-09-17 09:25
I think this issue can be closed and new issues can be opened for other problems.

**Comment by iandwelker** [comment] 2020-09-17 14:52
Ok, well this is good to know. I use iCloud photos as well, but I do have them all downloaded so that's probably why I don't run into this issue. Although I can look into it, I think it may just not be possible to get the URL of a photo that's only in iCloud through public APIs (and using private APIs would require using IPC to get every single URL, significantly slowing down the program). I'll keep this issue open for a bit while I look into this, and update if I find anything.

**Comment by londondev77** [comment] 2020-09-17 18:37
I wasn't aware that the few photos I have were from iCloud. I switched off iCloud photos, took a new photo and it showed up fine in the web interface. So I think this can be closed.

**Comment by iandwelker** [comment] 2020-09-18 16:34
Alright, if you're all ok with it, I'll close the issue.

**Closed by iandwelker** 2020-09-18 16:34 UTC
