### ISSUE TITLE
Crash when selecting conversations

### ISSUE THREAD

**Issue by BinuwaraN** [iandwelker/smserver#27] opened 2020-08-28 10:11 UTC
Device model: iPad (6th generation)
Jailbreak: Unc0ver 5.3.1
iOS Version: 13.5
How you installed the app: Cydia
SMServer version: 0.3.5

When clicking on a conversation in the web app cause a crash in the mobile app.
[Crash Log](https://github.com/iandwelker/smserver/files/5141464/crash_log.txt)

**Comment by iandwelker** [comment] 2020-08-28 17:29
Could you try disabling the `mark conversations as read...` toggle in the settings of the app, restarting the app, and see then if the issue still persists?

**Comment by BinuwaraN** [comment] 2020-08-28 20:42
Disabling `Mark conversations as read when viewed on web interface` stops the app from crashing.

**Comment by iandwelker** [comment] 2020-08-28 22:09
Alright, I'm fairly certain I know what the issue is, then. It should be fixed in the next version, and I'll update this issue once I release it.

**Comment by iandwelker** [comment] 2020-08-29 00:03
Version 0.3.6 is out; Once it becomes available for you, could you try it out and let me know if you still run into this when `Mark conversations as read when viewed on web interface` is enabled?

**Comment by BinuwaraN** [comment] 2020-08-29 03:20
The issue is fixed after 0.3.6v. However when selecting on the camera roll button cause the app to crash.
[crash_log](https://github.com/iandwelker/smserver/files/5144729/crash_log.txt)

**Closed** 2020-08-29 10:09 UTC
