### ISSUE TITLE
Issues with SMServer

### ISSUE THREAD

**Issue by vugi99** [iandwelker/smserver#38] opened 2020-09-17 19:50 UTC
Iphone X, IOS 13.7, Checkra1n, SMServer 0.4.2, libsmserver 0.3.5, installed with Zebra

First, the tweak is not working for me (infinite loading page even after 3 reboots and rejailbreak)
But the worst thing is that i noticed cellular and wifi problems and SMServer seems to be the culprit

**Comment by iandwelker** [comment] 2020-09-18 00:20
With regard to the page not loading, there are a few things you should check:
1. Have you made sure to install all of the dependencies (specifically `libsmserver` and `libMRYIPC`)?
1. Did you start the server with the green button on the bottom left of the app?
1. Are you connecting to the right address with regard to using `https://` vs `http://`?
1. Are your host and client devices on the same LAN/WLAN networks?
1. Did you verify that neither device's firewall is blocking the connection?

What sort of cellular/wifi problems are you running into? And what leads you to believe that SMServer is the culprit?

**Comment by vugi99** [comment] 2020-09-18 06:18
1. Yes
2. Yes
3. It works now, but i need to disable SSL and connect with http://
4. Yes
5. I don't have any firewall or vpn on my device
I will test more to be sure it was the culprit

**Comment by iandwelker** [comment] 2020-09-21 18:10
If you update to the latest version of SMServer, can you still not connect without disabling SSL?

**Comment by vugi99** [comment] 2020-09-21 20:54
> If you update to the latest version of SMServer, can you still not connect without disabling SSL?
No, i can't connect without disabling SSL.

**Comment by iandwelker** [comment] 2020-09-23 00:43
Sorry about the lapses in response, I've just not been able to make much progress on this issue. Did you happen to make any more progress on determining if SMServer was the culprit of your wifi/cellular issues?

**Comment by vugi99** [comment] 2020-09-23 17:14
It seems that SMServer was not the culprit

**Comment by iandwelker** [comment] 2020-10-02 17:22
Do you think you could try importing the certificate into your computer's certificate trust (you can download it from `src/SMServer/cert.der` in this repo) and then connecting via `https://` and with SSL on?

**Comment by vugi99** [comment] 2020-10-02 18:38
It works now but it says that the certificate is still invalid

**Comment by iandwelker** [comment] 2020-10-02 18:41
If it connects through `https://` but still says the certificate is invalid, that's totally expected behavior. It says the site is not secured because the site that the certificate was registered for does not match the site that the certificate is being used for, but that's exactly how I made it and intended it to be used. I'll close this issue, then; feel free to re-open if you run into this issue again.

**Closed by iandwelker** 2020-10-02 18:41 UTC
